name: 📃 Guide Issue Report
description: Report issues or suggest changes for guides.
title: "Guide Amendment: "
labels: "type | guide-problem"
body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting an issue with a guide.

        Please fill out the template below to make it easier to work on your issue.

  - type: checkboxes
    attributes:
      label: Preflight Checklist
      description: Please ensure you've completed all of the following.
      options:
        - label: I have searched for existing issues and cannot find mine, or existing issues do not fit.
          required: true

  - type: input
    attributes:
      label: Name of Guide?
    validations:
      required: true

  - type: input
    attributes:
      label: Language of Guide?
    validations:
      required: true

  - type: textarea
    attributes:
      label: Summary of Issue / Changes
    validations:
      required: true

  - type: textarea
    attributes:
      label: Your Suggested Changes (in full)
    validations:
      required: true
