name: "PR: JSON Changes"

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    paths:
      - "**.json"
    types: [ready_for_review, opened, synchronize, reopened]

jobs:
  Validate:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Validate JSON Syntax
        uses: limitusus/json-syntax-check@v1
        with:
          pattern: "\\.json$"
